# Define and execute multiple Docker Containers
version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: myapp_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}    
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} 
      POSTGRES_DB: ${POSTGRES_DB}           
    ports:
      - "5432:5432" # map from local port to container port
    command: >
      bash -c "
        docker-entrypoint.sh postgres &
        sleep 5 &&
        psql -U $POSTGRES_USER -d $POSTGRES_DB -c 'CREATE DATABASE myapp_test;' || true &&
        wait
      "