### Get all couriers
GET http://localhost:3333/couriers
Content-Type: application/json

###

### Create a new courier
POST http://localhost:3333/couriers
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john.doe@example.com"
}

###

### Get courier by ID
GET http://localhost:3333/couriers/e8303320-569a-4863-8476-5169b1a410da
Content-Type: application/json
