### Get all deliveries
GET http://localhost:3333/deliveries
Content-Type: application/json

###

### Create a new delivery
POST http://localhost:3333/deliveries
Content-Type: application/json

{
  "item": "Item three",
  "destinyAddress": "123 Main St",
  "courierId": "e8303320-569a-4863-8476-5169b1a410da",
  "status": "PENDING"
}

###

### Get delivery by ID
GET http://localhost:3333/deliveries/b98b94b6-f7bb-4a78-a8d7-88fe47d94ac0
Content-Type: application/json

###

### Get all deliveries by courier ID
GET http://localhost:3333/deliveries/courier/e8303320-569a-4863-8476-5169b1a410da
Content-Type: application/json

###

### Update delivery status
PATCH http://localhost:3333/deliveries/7e111a12-62c2-4479-aa86-d98b6927afc5
Content-Type: application/json

{
  "status": "COMPLETED"
}
