apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_USER: myuser
  POSTGRES_PASSWORD: mypassword
  POSTGRES_DB: myapp
  DATABASE_URL: postgresql://myuser:mypassword@postgres:5432/myapp?schema=public
